---

- name: Basic setup
  remote_user: root
  hosts: all
  tasks:
    - name: Updating apt cache
      apt: update_cache=yes
    - include: tasks/users.yml
    - include: tasks/hostname.yml
    - include: tasks/locale.yml
    - include: tasks/motd.yml
    - include: tasks/essential_commands.yml

- name: Installing necessary bells and whistles
  remote_user: kjetil
  hosts: all
  tasks:
    - include: tasks/keys.yml
    - include: tasks/github.yml
    - include: tasks/dotfiles.yml
