---
- include: basic.yml

- name: Installing necessary bells and whistles
  remote_user: kjetil
  hosts: all
  tasks:
    - include: tasks/install_nginx.yml
    - include: tasks/blog.yml
  handlers:
    - name: reload nginx
      service: name=nginx state=reloaded
      sudo: yes

- name: Installing and configuring Cellarium
  remote_user: root
  hosts: all
  tasks:
    - include: tasks/cellarium.yml
    - include: tasks/git.yml
  handlers:
    - name: reload nginx
      service: name=nginx state=reloaded
    - name: restart cellarium
      service: name=cellarium state=restarted
