---
- include: basic.yml

- name: Installing necessary bells and whistles
  hosts: all
  tasks:
    - include: tasks/install_nginx.yml
    - include: tasks/blog.yml
    - include: tasks/git.yml
  handlers:
    - name: reload nginx
      service: name=nginx state=reloaded
      sudo: yes
  remote_user: kjetil

- name: Installing and configuring Cellarium
  hosts: all
  remote_user: root
  tasks:
    - include: tasks/cellarium.yml
  handlers:
    - name: reload nginx
      service: name=nginx state=reloaded
    - name: restart cellarium
      service: name=cellarium state=restarted
