- name: installing basic commands
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - git
    - zip
    - tree
    - vim
    - curl
    - screen
    - irssi
    - python-pip
    - python-virtualenv
    - inotify-tools
  sudo: yes
