- name: Copy blog nginx config
  copy: src=nginx/blog.conf dest=/etc/nginx/sites-available/default.d/blog.conf owner=root mode=755
  notify:
    - reload nginx
  sudo: yes

- name: Create directory for hosting blog
  file: name=/home/kjetil/blog/ state=directory recurse=yes
