- name: Copy cellarium nginx config
  copy: src=nginx/cellarium.conf dest=/etc/nginx/sites-available/default.d/cellarium.conf owner=root mode=755
  notify:
    - reload nginx
  sudo: yes

- name: Git clone cellarium repo
  action: git repo=git@github.com:kvalle/cellarium.git dest=/home/kjetil/cellarium

- name: Installing build-essential
  apt: pkg=build-essential state=installed
  sudo: yes

- name: Installing python-dev
  apt: pkg=python-dev state=installed
  sudo: yes

- name: Installing uwsgi and uwsgitop
  pip: name={{item}}
  sudo: yes
  with_items:
    - uwsgi
    - uwsgitop

- name: Installing cellarium requirements
  pip: requirements=/home/kjetil/cellarium/server/requirements.txt
  sudo: yes
