- name: Copy cellarium nginx config
  copy: src=cellarium/nginx/cellarium.conf dest=/etc/nginx/sites-available/default.d/cellarium.conf owner=root mode=755
  notify:
    - reload nginx

- name: Ensure /var/www is created
  file: path=/var/www state=directory

- name: Git clone cellarium repo
  git: repo=git@github.com:kvalle/cellarium.git dest=/var/www/cellarium key_file=/home/kjetil/.ssh/id_rsa accept_hostkey=yes

- name: Ensure www-data ownership of cellarium home
  file: path=/var/www/cellarium owner=www-data group=www-data recurse=yes

- name: Installing build-essential
  apt: pkg=build-essential state=installed

- name: Installing python-dev
  apt: pkg=python-dev state=installed

- name: Installing uwsgi and uwsgitop
  pip: name={{item}}
  with_items:
    - uwsgi
    - uwsgitop

- name: Installing cellarium requirements
  pip: requirements=/var/www/cellarium/server/requirements.txt

- name: Creating log directory for uwsgi/cellarium
  file: path=/var/log/uwsgi state=directory

- name: Create /etc/cellarium
  file: path=/etc/cellarium state=directory

- name: Copy cellarium uwsgi.ini file
  copy: src=cellarium/uwsgi/cellarium.ini dest=/etc/cellarium/uwsgi.ini owner=root mode=644

- name: Copy cellarium upstart
  copy: src=cellarium/upstart/cellarium.conf dest=/etc/init/cellarium.conf owner=root mode=644
  notify:
    - restart cellarium
