- name: add github to known_hosts
  shell: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
- name: Git clone dotfiles repo
  action: git repo=git@github.com:kvalle/dotfiles.git dest=/home/kjetil/dotfiles
- name: Ensure pip installed PyYAML
  pip: name=PyYAML
  sudo: yes
- name: symlink dotfiles
  shell: > 
    /home/kjetil/dotfiles/symlink.py && touch /home/kjetil/dotfiles/.created 
    creates=/home/kjetil/dotfiles/.created
