- name: Install Git
  apt: pkg=git state=installed

- name: Create user 'git'
  user: name=git password=ejJSBLcTVQ2O6 state=present shell=/bin/bash

- name: Create folder for repos
  file: name=/var/git/ state=directory recurse=yes owner=git
