- name: Install update-motd
  apt: pkg=update-motd state=installed update_cache=yes
- name: Copy new motd file
  copy: src=motd dest=/etc/update-motd.d/10-motd owner=root mode=755
- name: reading 'update-motd.d' files
  shell: ls -1 /etc/update-motd.d/*
  register: motd_contents
  changed_when: no
- name: removing files from 'update-motd.d'
  file: name=/etc/update-motd.d/{{ item }} state=absent
  with_items: motd_contents.stdout_lines
  when: "'10-motd' not in '{{ item }}'"
- name: "set sshd_config, PrintLastLog no"
  lineinfile: >
    dest=/etc/ssh/sshd_config 
    regexp="^PrintLastLog" 
    line="PrintLastLog no"
  register: ssh_conf
- name: restart ssh
  service: name=ssh state=reloaded
  when: ssh_conf.changed
